/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddPackageDialog: typeof import('./src/components/containers/DialogAddPackage.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    DialogAddPackage: typeof import('./src/components/containers/DialogAddPackage.vue')['default']
    DialogDeleteComfirm: typeof import('./src/components/containers/DialogDeleteComfirm.vue')['default']
    DialogPythonPackage: typeof import('./src/components/containers/DialogPythonPackage.vue')['default']
    DialogPythonPackageUpdate: typeof import('./src/components/containers/DialogPythonPackageUpdate.vue')['default']
    PythonPackages: typeof import('./src/components/containers/PythonPackages.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
