/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    BtnTheme: typeof import('./src/components/plugins/BtnTheme.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    DialogAddPackage: typeof import('./src/components/containers/DialogAddPackage.vue')['default']
    DialogDeleteComfirm: typeof import('./src/components/containers/DialogDeleteComfirm.vue')['default']
    DialogPipConfig: typeof import('./src/components/containers/DialogPipConfig.vue')['default']
    DialogPythonPackage: typeof import('./src/components/containers/DialogPythonPackage.vue')['default']
    DialogPythonPackageUpdate: typeof import('./src/components/containers/DialogPythonPackageUpdate.vue')['default']
    DockerManager: typeof import('./src/components/containers/container/DockerManager.vue')['default']
    PythonPackages: typeof import('./src/components/containers/PythonPackages.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemManager: typeof import('./src/components/system/SystemManager.vue')['default']
  }
}
